// Generated by CoffeeScript 1.4.0
var unanimity;

unanimity = function(backbone, db) {
  var Result;
  Result = (function() {

    function Result() {}

    Result.prototype.on = backbone.Events.on;

    Result.prototype.off = backbone.Events.off;

    Result.prototype.trigger = backbone.Events.trigger;

    Result.prototype.once = backbone.Events.once;

    return Result;

  })();
  backbone.sync = function(method, model, options) {
    var id, result, rev, update;
    result = new Result;
    id = null;
    if (model.id !== void 0) {
      id = model.id;
    }
    update = {};
    if (method === 'update' || method === 'create' || method === 'patch') {
      db.insert(model.toJSON(), id, function(err, body) {
        if (err) {
          if (typeof options.error === 'funciton') {
            options.error(model, err, options);
            return;
          } else {
            throw err;
          }
        }
        update['_rev'] = body.rev;
        if (id === null) {
          update[model.idAttribute] = body.id;
        }
        options.success(model, update, options);
        model.trigger('sync', model);
        return result.trigger('success', model);
      });
    } else if (method === 'read') {
      if (id === null) {
        throw "Can't fetch a model without id!";
      }
      db.get(id, function(err, body) {
        var key, value;
        if (err) {
          if (typeof options.error === 'funciton') {
            options.error(model, err, options);
            return;
          } else {
            throw err;
          }
        }
        for (key in body) {
          value = body[key];
          if (key !== '_id') {
            update[key] = value;
          }
        }
        options.success(model, update, options);
        return result.trigger('success', model);
      });
    } else if (method === 'delete') {
      rev = model.get('_rev');
      if (id === null) {
        throw "Can't destroy a model without id!";
      }
      if (typeof rev !== 'string') {
        throw "Can't destroy a new model!";
      }
      db.destroy(id, rev, function(err, body) {
        if (err) {
          if (typeof options.error === 'funciton') {
            options.error(model, err, options);
            return;
          } else {
            throw err;
          }
        }
        options.success(model, update, options);
        return result.trigger('success', model);
      });
    }
    return result;
  };
  return backbone.sync.db = db;
};

module.exports = unanimity;
